<?php
namespace Magenest\UltimateFollowupEmail\Model\Coupon;

class Massgenerator extends \Magento\SalesRule\Model\Coupon\Massgenerator
{
    /**
     * @param $ruleId
     * @param $qty
     * @param $mailId
     * @param $expiredTime
     * @param $sendDate
     * @return array
     * @throws \Magento\Framework\Exception\LocalizedException
     */
    public function generateFuePool($ruleId, $qty, $mailId, $expiredTime, $sendDate)
    {
        $this->generatedCount = 0;
        $this->generatedCodes = [];
        $maxAttempts = $this->getMaxAttempts() ? $this->getMaxAttempts() : self::MAX_GENERATE_ATTEMPTS;
        $this->increaseLength();
        /** @var $coupon \Magento\SalesRule\Model\Coupon */
        $coupon = $this->couponFactory->create();
        $nowTimestamp = $this->dateTime->formatDate($sendDate);

        for ($i = 0; $i < $qty; $i++) {
            $attempt = 0;
            do {
                if ($attempt >= $maxAttempts) {
                    throw new \Magento\Framework\Exception\LocalizedException(
                        __('We cannot create the requested Coupon Qty. Please check your settings and try again.')
                    );
                }
                $code = $this->generateCode();
                ++$attempt;
            } while ($this->getResource()->exists($code));
            $expirationDate = new \DateTime($nowTimestamp);

            if (isset($expiredTime['day']) && isset($expiredTime['hour']) && isset($expiredTime['minute'])) {
                $time = 'P';
                $time .= $expiredTime['day'] ? $expiredTime['day'].'D' : '';
                $time .= $expiredTime['hour'] || $expiredTime['minute'] ? 'T': '';
                $time .= $expiredTime['hour'] ? $expiredTime['hour'].'H' : '';
                $time .= $expiredTime['minute'] ? $expiredTime['minute'].'M' : '';
                if ($expiredTime['day'] || $expiredTime['hour'] || $expiredTime['minute']) {
                    $expirationDate->add(new \DateInterval($time));
                    $expirationDate = $expirationDate->format('Y-m-d H:i:s');
                } else {
                    $expirationDate = null;
                }
            }

            $coupon->setId(null)
                ->setRuleId($ruleId)
                ->setUsageLimit($this->getUsesPerCoupon())
                ->setUsagePerCustomer($this->getUsagePerCustomer())
                ->setExpirationDate($expirationDate)
                ->setCreatedAt($nowTimestamp)
                ->setMailId($mailId)
                ->setType(\Magento\SalesRule\Helper\Coupon::COUPON_TYPE_SPECIFIC_AUTOGENERATED)
                ->setCode($code)
                ->save();

            $this->generatedCount += 1;
            $this->generatedCodes[] = $code;
        }

        return $this->generatedCodes;
    }
}
